### ISSUE TITLE
运行即闪退哦

### ISSUE THREAD

**Issue by FmLe** [relish-wang/VehicleEditText#4]
## 型号：
    HUAWEI EVA-AL00, HUAWEI NXT-AL10；都是8.0

## log
     android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:884)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:372)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:128)
        at android.widget.PopupWindow.invokePopup(PopupWindow.java:1462)
        at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1231)
        at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1198)
        at wang.relish.widget.vehicleedittext.VehicleKeyboardHelper.showCustomInput(VehicleKeyboardHelper.java:244)
        at wang.relish.widget.vehicleedittext.VehicleKeyboardHelper.access$200(VehicleKeyboardHelper.java:52)
        at wang.relish.widget.vehicleedittext.VehicleKeyboardHelper$3.onFocusChange(VehicleKeyboardHelper.java:151)
        at android.view.View.onFocusChanged(View.java:6959)
        at android.widget.TextView.onFocusChanged(TextView.java:9836)
        at android.view.View.handleFocusGainInternal(View.java:6631)
        at android.view.View.requestFocusNoSearch(View.java:10890)
        at android.view.View.requestFocus(View.java:10869)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3217)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3173)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3217)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3173)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3217)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3173)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3217)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3173)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3217)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3173)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3217)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3176)
        at android.view.View.requestFocus(View.java:10836)
        at android.view.View.requestFocus(View.java:10778)
        at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:3704)
        at android.view.View.setFlags(View.java:13392)
        at android.view.View.setVisibility(View.java:9417)
        at android.app.Activity.makeVisible(Activity.java:5793)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4438)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3423)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)

**Comment by relish-wang** [comment]
在调试中复现了此bug，已尝试进行修复。因手上没有你所提供的手机型号，故未对针对的型号进行验证。你可以依赖最新的版本进行验证。谢谢。
